### ISSUE TITLE
Add a way to render a subset of a PDF page

### ISSUE THREAD

**Issue by dalewking** [rbcprolabs/flutter_plugins#2]
**Package name**
native_pdf_renderer

**Describe the solution you'd like**
To be able to specify a rectangle in the coordinates of the PDF page to specify what to render.

**Describe alternatives you've considered**
The alternative is to render the entire page and then copy the part you want.

**Comment by SergeShkurko** [comment]
will be added in #11

**Comment by SergeShkurko** [comment]
Added in v `1.5.0`
