### ISSUE TITLE
Error on iOS build

### ISSUE THREAD

**Issue by yostrokon** [rbcprolabs/flutter_plugins#3]
[!] Unable to determine Swift version for the following pods:

    - `native_pdf_renderer` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

what should i do?

**Comment by SergeShkurko** [comment]
@yostrokon you need set swift version to `5` by [instruction](https://stackoverflow.com/a/46339401/6858892)

**Comment by SergeShkurko** [comment]
If the error does not disappear, try this [instruction](https://stackoverflow.com/a/47530482/6858892) as well

**Comment by SergeShkurko** [comment]
@yostrokon problem solved? If not, contact me with a name here, I will reopen the issue.

**Comment by yostrokon** [comment]
@SergeShkurko tried to copy the Podfile from your sample adding 
      config.build_settings['SWIFT_VERSION'] = '5'  # required
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
and build using codemagic, but no success, same response, may be missing something somewhere else

**Comment by yostrokon** [comment]
@SergeShkurko 
  - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `native_pdf_renderer` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by yostrokon** [comment]
@SergeShkurko added swift 5, but now surprised by
Xcode's output:
↳

                    data = UIImagePNGRepresentation(image) as Data?
                           ^~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~
                           image.pngData            
    UIKit.UIImagePNGRepresentation:2:13: note: 'UIImagePNGRepresentation' was obsoleted in Swift 3

**Comment by SergeShkurko** [comment]
@yostrokon, what version `native_pdf_renderer` are you using?

**Comment by yostrokon** [comment]
@SergeShkurko 
update to the newer version fixed all things, thanks for support
