### ISSUE TITLE
Build error in native_pdf_renderer plugin on Swift 4.2

### ISSUE THREAD

**Issue by stenionobresem** [rbcprolabs/flutter_plugins#7]
**Package name**
native_pdf_renderer v1.3.0+1

**Describe the bug**

=== BUILD TARGET native_pdf_renderer OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/escolarmanager/work/flutter_plugins_pdf/packages/native_pdf_renderer/ios/Classes/document/Page.swift:59:30: error: 'pngData()' has been renamed to
    'UIImagePNGRepresentation(_:)'
                    data = image.pngData() as Data?
                                 ^~~~~~~
                                 UIImagePNGRepresentation
    UIKit.UIImage:58:17: note: 'pngData()' was introduced in Swift 4.2
        public func pngData() -> Data?

**To Reproduce**
1. Create a new flutter project;
2. Adds native_pdf_renderer v1.3.0+1 plugin to pubspec.yaml
3. Run **flutter build ios** command

**Expected behavior**
Successful build

**Smartphone (please complete the following information):**
 - MAC OS Mojave 10.14.5
 - XCODE Version 10.1 (10B61)
 - Swift 4.2

**Additional context**
I was replaced the 59 line of **Page.swift** file and the build works!!!

original 
`data = image.pngData() as Data?`

suggestion
 `data = UIImagePNGRepresentation(image)`

**Could you please publish the correction in pub.dev?**

Thanks in advance

**Comment by SergeShkurko** [comment]
@stenionobresem see #3
